### ISSUE TITLE
Question about CONFLICT_FREE_OFFSET(n)

### ISSUE THREAD

**Issue by lsl036** [GPUPeople/spECK#9]
I have noticed that in include/GPU/scan_largearray_kernel.cuh , it defines like：
`#define NUM_BANKS 32U`
`#define LOG_NUM_BANKS 6U`, where I think the LOG should be `5U`.

In addition, the definition of `CONFLICT_FREE_OFFSET (n)` seems always equal to zero because the "+" has higher precedence than ">>".
![image](https://user-images.githubusercontent.com/34669680/181508401-b4a39d3a-43e8-4647-99ca-421c5fdc3512.png)

I check [here](https://stackoverflow.com/questions/9689185/conflict-free-offset-macro-used-in-the-parallel-prefix-algorithm-from-gpu-gems-3) but have no idea about this bank conflict-free operation.

I try to adjust this definition to:
![image](https://user-images.githubusercontent.com/34669680/181508629-197d29cb-5f50-4308-a7fc-b1d03d97925a.png)
Then it seems that illegal memory access is generated somewhere.
Any help for my understanding of this part of code? Does `CONFLICT_FREE_OFFSET` truly work?
I am looking forward to your reply!

**Comment by dabeschte** [comment]
Haha, that's an interesting one. You are right of course.
First of all, log(32)=5. But it does not really matter, because the conflict_free_offset always returns zero anyways.

I relied on the code from [here](https://raw.githubusercontent.com/phebuswink/CUDA/master/MP4/MP4.2/scan_largearray_kernel.cu) and [here](https://github.com/dhoeflinger/CUDA/tree/master/MP4/MP4.2). 
Both seem to be using the bank conflict avoidance equation for prefix sums from [GPUGems 3](https://developer.nvidia.com/gpugems/gpugems3/part-vi-gpu-computing/chapter-39-parallel-prefix-sum-scan-cuda).

I simply used it and never cared about what it does exactly since the code was working as is. But now that I dig into it, it does not really work at all the way I use it with bank widths of 32...and it also is not required for this project.
With 32 bit integers, n >> 32 will always be zero. And without adding brackets around the first and second half of the addition, 

I quickly debugged this on [onlinegdb](https://onlinegdb.com/DG15xN9Gt) and it seems to be completely useless. Here, I can't even compile it without using 64 bit integer values as input.

So, no, it does not work. Nsight Compute also tells me that there are some bank conflicts. 
Since this kernel is already quite fast, however, I think it is not worth investigating time to fix them. I replaced the macro by a constant 0 to make sure that no compilation errors pop up.
